[WIP] Renderer fixed.
joel16/SDL2 pull request #5
Opened 2020-12-26 11:51 UTC by stdgregwar

This fixes the behavior of the renderer. Making it behave like 2.0.9.
There are still changes that are to be made : 
[ ] Support render to texture
[ ] Support for 16bit display instead of 32bit default

2020-12-26 23:25 UTC, sharkwouter commented
Wow, thanks for working on this. I've been hoping someone would figure this out.

So far I've managed to compile this and use it to draw a texture on the screen. Unscaled textures seems to work fine at the moment.

I'll need more time to properly test this, but since you're also still working on this I'd say that fits.

2021-01-11 09:04 UTC, sharkwouter commented
Thanks for the continued work. I will see if I can test this again tomorrow and I'll let you know my findings. I was trying to build [this code](https://github.com/sharkwouter/panel-pop/tree/psp-port) with it, but since it isn't finished it is hard to say when something is broken if it is SDL or my code. I'll try again

2021-01-12 21:21 UTC, sharkwouter commented
I just tested this again and I'm blown away. It actually works really well. I compiled panel-pop and played it. It actually works, images are draw like expected, no out of memory issues. The only problem I've seen is that sdl2_ttf shows artifacts on some of the drawn text, but I'm not sure if that is related. I've tested this with sdl2_ttf and sdl2_mixer.

2021-01-13 09:23 UTC, stdgregwar commented
I also tested this quite a lot on [Solarus](https://gitlab.com/solarus-games/solarus). I still have out of memory but it is because of other part of the engine code. The render to texture is still not exactly okay. I think it goes wrong when spilling something to sys ram at the same time it was rendered to in the frame (which is anyway super bad sign for performance). Will investigate. But for "normal" usage with regular drawing to display it seems stable and correct.

2021-01-13 12:13 UTC, sharkwouter commented
The only thing I miss in this branch is support for building with CMake, which is in the 2.0.9 port. That port doesn't work very well in general, though, what has been build in this PR should replace it.

Maybe you can try to see if you can cherry-pick this commit: https://github.com/joel16/SDL2/commit/768e689ab7b38edb49931c4f211bf1e7275f5828

If it doesn't work, I can fix it again later after this PR has been merged.

2021-01-15 19:23 UTC, stdgregwar commented
I think it would be better to cherry pick the commit afterward no ? Since it is pretty unrelated to the PR.

2021-01-16 13:40 UTC, sharkwouter commented
That is true

2021-01-18 12:52 UTC, sharkwouter requested changes
Well, I'm not really able to review as well as I would've liked, I'm just not familiar enough with the code, but I did find some small style issues. I've also used the resulting library in one of my projects and it works well. At the very least it's a big improvement over the old code and worth merging after addressing why I found at this point.

2021-01-18 12:52 UTC, sharkwouter commented on src/render/psp/SDL_render_psp.c
> +
This seems out of place

2021-01-18 12:52 UTC, sharkwouter commented on src/render/psp/SDL_render_psp.c
> +            //data->frontbuffer = (unsigned int *)(PSP_FRAME_BUFFER_SIZE<<1);
We better exclude commented out code all together.

2021-01-18 12:52 UTC, sharkwouter commented on src/render/psp/SDL_render_psp.c
> +                /* Viewport */
This comment is unnecessary.

2021-01-22 13:49 UTC, sharkwouter approved these changes

2021-01-22 15:21 UTC, merged